### ISSUE TITLE
Question: probe/flashing

### ISSUE THREAD

**Issue by nebelgrau77** [pbert519/nrf52840-embassy#2]
Hi,

Quick question: what are you using to communicate with the board? I see that it's the "full" Feather, so I suppose it has the JTAG header and you're using J-Link? I have the ItsyBitsy Express board and rely on the bootloader, which I have rebuilt with S140 v.7.3.0, but so far no luck. Thanks in advance for the info!

**Comment by pbert519** [comment]
Hi,
i'm using a jlink jtag probe with the board.
The board does not have a jtag header (only the normal feather has one, but not the sense), but jtag pads and i soldered some extension cables to it.
I have not tried the bootloader yet, but it is on the TODO list. I assume you mean the embassy-boot bootloader?

good luck to get it up and running!

**Comment by nebelgrau77** [comment]
Hi, thanks for the answer! Oh I see, I didn't know the Sense board! I also have the SparkFun MicroMod with the JTAG header present on the carrier board, so I might try that. As for the bootloader, I meant this Adafruit bootloader: https://github.com/adafruit/Adafruit_nRF52_Bootloader
So my flashing procedure is: build, objcopy to hex, then convert to zip and flash with adafruit-nrfutil. It works with standard Rust code, but so far no luck with Embassy.
